### ISSUE TITLE
Server Behaviour Model

### ISSUE THREAD

**Issue by rowanchase** [justinyhuang/yams#7]
Firstly, thanks for writing such a high quality and user friendly modbus sim.  Other open source options I've tried have been tedious or didn't work at all, so thank you.

I was wondering if you had any thoughts about if/how a server behaviour model could be implemented with yams?

For example, I would like to simulate a PLC controlling a VFD:

- When a 1 is written to the 'control' register the 'speed' and 'frequency' registers should gradually ramp up to the 'set point' register value.
- Equally, when 0 is written to the control register, they should ramp down to 0

Is this something already possible, you have a vision for or explicitly not in scope?

Thanks,

**Comment by justinyhuang** [comment]
Sorry if I reply late: for some reason I have not been notified about this open issue.
I guess I am not sure that I understand your question, so please first help me with your question:
* Is this scenario you described based on Modbus?
* If yes:
    * what is the master/client and what is the slave/server of this Modbus communication?
    * what does the request/response look like in Modbus terminology? for example: is it a request to write some holding registers?

I appreciate your interest and please let me know if I can help with anything further.

Cheers,

**Comment by justinyhuang** [comment]
After reading your comment again I think I understand what you mean: updating some register/coil value in a Modbus server could trigger some operations defined by the user.
I believe it is feasible but non-trial: basically what we can do is to share real-time server data (like save as a file) so that external scripts/tools can modify, and to allow calling the corresponding script/tool when certain register/coil has been set/updated. The assigned scripts/tools would be able to update any values per application.
For now I think I can put it into the TODO list and implement it later. 
Having said that, I would be more than happy to review and integrate an PR from whoever'd like to help with YAMS ;)

**Comment by rowanchase** [comment]
> updating some register/coil value in a Modbus server could trigger some operations defined by the user.

Yes, this is what I meant.

For some more context -> I work for a company doing agricultural automation.  It would be very handy if we could simulate an irrigation pump controller in a realistic manner such that we can test our entire application from firmware right up to the UI.

I don't write a lot of rust, however I'd certainly be willing to have a go at the problem if you have some ideas about how to go about it.

**Comment by justinyhuang** [comment]
OK I have added a TODO in [this commit](https://github.com/justinyhuang/yams/commit/d8a3e07f33145b3e9d2d1613967982d8434301e2#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R51). 
I think a possible breakdown could be:
1. move the server data storage to an individual file
2. with change in step 1 we will also need to change the way we access the register/coil data to file accesses (a bonus of doing so is that the server data could be preserved across test runs)
3.  to add a field (or fields) to the server data attribute to allow calling external tools when an item is updated.
4.  we might want to make this behavior optional driven by some user input.

I am not a Rust expert so any help/suggestion would be great, if not that's OK: I plan to implement this feature just not sure when I could make it.

Please feel free to reach out anytime.

Cheers,

**Comment by justinyhuang** [comment]
FYI I have started working on this request. Not sure when it would be available though ;)

**Comment by rowanchase** [comment]
Oh excellent, thank you!  I was hoping to get to it, but have not found time so far.  I'll be happy to help test it out or anything else you might need.

**Comment by justinyhuang** [comment]
OK, I have something that might work for you ;)
Would you mind building YAMS from [this branch](https://github.com/justinyhuang/yams/tree/server.data.update.triggered.by.register.writes) and see if it works?

You might like to take a look at the `modbus.tcp.server.flow.config.yaml`, `modbus.tcp.client.normal.config.yaml` and `update.power.state.led.py` to get some ideas. Basically what it does is:
1. the client sets/clears the "power button coil"
2. the server will update the state of the "power led coil" based on the value of the "power button coil", implemented in the Python script.
3. YAMS will pick up the changes by the external program.

Edit: I also uploaded a new demo

**Comment by justinyhuang** [comment]
I am closing this ticket with the release of v0.9.
However, feel free to reach out for any issues or questions.

**Comment by rowanchase** [comment]
This looks really really neat, thank you!
